# Generated by Django 5.2.6 on 2025-10-25 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Sl_No',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='case_number',
        ),
    ]
