# Generated by Django 5.2.6 on 2025-10-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_remove_patient_sl_no_remove_patient_case_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AddField(
            model_name='patient',
            name='Sl_No',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
