# Generated by Django 5.2.6 on 2025-10-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_remove_patient_id_patient_sl_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Sl_No',
        ),
        migrations.AddField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
