# Generated by Django 5.2.6 on 2025-10-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0016_remove_appointment_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
