# Generated by Django 5.2.6 on 2025-10-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0020_remove_appointment_appointment_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
