# Generated by Django 5.2.6 on 2025-10-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0021_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
    ]
