# Generated by Django 5.2.6 on 2025-10-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0023_remove_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_datetime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
