# Generated by Django 5.2.6 on 2025-10-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0024_appointment_appointment_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_datetime',
            new_name='appointment_date',
        ),
    ]
