# Generated by Django 5.2.6 on 2025-10-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0025_rename_appointment_datetime_appointment_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
