# Generated by Django 5.2.6 on 2025-10-27 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0027_remove_receptionist_password_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
