# Generated by Django 5.2.6 on 2025-10-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0028_remove_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('disease', models.CharField(max_length=200)),
                ('medicines', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
