# Generated by Django 5.2.6 on 2025-10-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0029_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
