# Generated by Django 5.2.6 on 2025-10-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0030_prescription_doctor_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialty',
            new_name='specialization',
        ),
    ]
